import Head from 'next/head';
import React, {ReactNode} from 'react';
import styled from 'styled-components';
import {Nav} from './Nav';

interface Props {
  children: ReactNode;
}

export const Layout = ({children}: Props) => {
  return (
    <Container>
      <Head>
        <title>Route Studio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main>{children}</main>
      <footer>
        <div>Footer</div>
      </footer>
    </Container>
  );
};

const Container = styled.div`
  background-color: #fff;
`;
